# Generated by Django 5.1.6 on 2025-02-18 17:59

import django.db.models.deletion
import parler.fields
import parler.models
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0002_alter_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('products_code', models.CharField(max_length=100)),
                ('tech_img', models.ImageField(blank=True, null=True, upload_to='product_tech_img')),
                ('tech_img_pro', models.ImageField(blank=True, null=True, upload_to='product_tech_img')),
                ('tech_img_pro2', models.ImageField(blank=True, null=True, upload_to='product_tech_img')),
                ('boot_description_title', models.CharField(max_length=250)),
                ('boot_description', models.TextField()),
                ('scope_of_using_img', models.ImageField(blank=True, null=True, upload_to='scope_of_using')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='categories.category')),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProductTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('short_description', models.TextField()),
                ('tech_desc', tinymce.models.HTMLField()),
                ('h2_title', models.CharField(max_length=250)),
                ('h3_title', models.CharField(max_length=250)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='products.product')),
            ],
            options={
                'verbose_name': 'product Translation',
                'db_table': 'products_product_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
