# Generated by Django 5.1.6 on 2025-02-18 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='boot_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='boot_description_title',
        ),
        migrations.AddField(
            model_name='producttranslation',
            name='boot_description',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='producttranslation',
            name='boot_description_title',
            field=models.CharField(default='N/A', max_length=250),
        ),
    ]
